{% set version = "1.32" %}
package:
  name: mutagen
  version: {{ version }}

source:
  fn: mutagen-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mutagen/mutagen-{{ version }}.tar.gz
  sha256: 7721ded04caf36fc30661165ae311fed342f7503b048e9db3d52764108ed3ab5

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - mutagen
    - mutagen.asf
    - mutagen.id3
    - mutagen.mp4

about:
  home: https://github.com/quodlibet/mutagen
  license: GNU General Public License v2 (GPLv2)
  summary: 'Read and write audio tags for many formats'

extra:
  recipe-maintainers:
    - pmlandwehr
