{% set name = "mutagen" %}
{% set version = "1.41.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "dab6038c7f0e17c1b67fb8f56303e8be21e73ac47760f1a8e716856f1bdf5057" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - mutagen
    - mutagen.asf
    - mutagen.id3
    - mutagen.mp4

  commands:
    - mid3cp -h
    - mid3iconv -h
    - moggsplit -h
    - mutagen-inspect -h
    - mutagen-pony -h

about:
  home: https://github.com/quodlibet/mutagen
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'Read and write audio tags for many formats'
  dev_url: https://github.com/quodlibet/mutagen
  doc_url: https://mutagen.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
