{%set name = "mutagen" %}
{%set version = "1.37" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "539553d3f1ffd890c74f64b819750aef0316933d162c09798c9e7eaf334ae760" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  preserve_egg_dir: True
  number: {{ build_num }}
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - mutagen
    - mutagen.asf
    - mutagen.id3
    - mutagen.mp4

  commands:
    - mid3cp -h
    - mid3iconv -h
    - moggsplit -h
    - mutagen-inspect -h
    - mutagen-pony -h

about:
  home: https://github.com/quodlibet/mutagen
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'Read and write audio tags for many formats'
  dev_url: https://github.com/quodlibet/mutagen
  doc_url: https://mutagen.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
