travis:
  secure:
    BINSTAR_TOKEN: vh/3wMOJ3l2Rn3R29hyxTc7L3lU+YfmKgzQaACyO3cg0hrhEcJyFFIdQUe7SVX7k+WYiT/Bz401AI+c+vDRT86NGMWl0dAWkTOHrL/I18tvz7ChBZYJ0Fkk4+Sx1NtosxzKWUM/EaDteror2c6CFYqmF+9rEQQarl9+nX9eFbiBTyx1t+j5hCLe5UTCVQjN5i8TMX286/StkwwdAd2htv3WeErvGiVlLfK6cZMkAdHk3ExZjDQw3St3N6SmfptUCccuEWLuxUJHLlHrUf8c2MM1EY3dI/77jSC8XjyAZVb2ve+r1EepiuCcew4gYGleD38/VTeRoMrvU/RaPY/x54Dpf5W677ZoY8ltlAzOh0OXkMGp9/WrmyfnIwt9h2cxqCRr9NcYNhJJv9/l1RYHa8XDizBo1UehptfYMMT/E6oigzZKO6c2ii84Ex8RN3S2vV9NpBPxJevBJdUuqSy9DSfdBd5zDsyhiTn/IA7NOkAO0ImoKG+zbtRBXFVdsOb6Q0+oo+LHLAQOcBgTRkssc3Ck/JB0gOeeiJnrW0dbqbbpISTMkv5krEKpi39MRncMrB+ptwQnNKaEW+F3L1nSXlybyFEmcsjrtAfECaPAMHskgSBbZJRQc507uthx+Iyfq3l/0aveT0aK31DwyWGWsY3K6EMDUFNTFdryMvlpSIDo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
