travis:
  secure:
    BINSTAR_TOKEN: b7cY+KlnkPVR22DnVgj+VAoUEZ3hh8e6xL5ZXPbONtP8XGMoB3GGB92mUshUyOPkvmcupiISig5ZoTSSPGH3Z7DZxSKH2e2eS89qYPW3+1H4TAF21Af6TXv+xq3vyk6jbr6+9Af5BRuGVBjMxvg+Brq0EcjagLMk14fS9DP5vPFTdYu7CgBJfUYqbSXgnbf+6Z+1h7wL8SbXYXIXSv7xBeP4voGsPw5u5bX+PmXg0ZRJcSvqwMcjrX0vAYg4OIrBB43ikRedb4B/wxvx/602vDMG7QMeqleBjoxDC1JPCY0c0ojZ037+jpRhYRLrHCHSgq8CPnUNTIp5/UrezaUgzF4jmMvAxqVXJoKZTmJQZtDsb5P2M/dyh36+tMR1YNl17JSFwbj8uKr1gNVO+/UVZGO+bExdhdmWTboqfe8HNSnqB3lMLR2RK9/AHrPgf2qO3dGtzZq5XVV+yaKw6DgL1PxnuNFW6iEapWg/gj9b9kc9V7+m11hlVqX8niiIYtZ/HUj9qEv0BHytKpjV0Ytm57LCFF2zv9iq98zShiirZpZwOA3NRAKa5G1h1ukzgAKcfwSiJNq+gsjiXYDZ5FtbgsFlpTeeICQ4OqzvfkQSBw6Ff1QgU8MkUKGb3R2O9lXCOwZEriwv0MmSOArdJPrNvveSW8zeMdFM+BfEoFArk3g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
