travis:
  secure:
    BINSTAR_TOKEN: NZByXLKMb419witmSSdO+1CYLmVww6FZDOTjK3WmLdOubccuKBjTepT2V+GXCgKx9ANf5p8foq3p3m8UzLGmlvRhNzXQj6c9C/wqbrqP8EvrT0nR+iwzIU7xcAFK53esCnXJA/qNYWifr+H+hl2e1XlGfa9LCS16rrcHj9H57ZZKo6nAnIvIHB8RJ0M3RG4ER6shVYwfH/ThSXnqJYKxjFCuIu0VDUMmbEccTXwq4g4K9cwkAan23A2Ts2MxCtPspnM0VrzqE67iiSXyv/aDGXy6/2SirZxxNFiKeMLbfN0bt+LFLxfTKLFQPCRzkTsCvSSTU57Xm6Ll+hznTVjHb1XlKcRi/AHF2j5/ifucBSIjcAb5fDHWC6c2XQrckt/WwcsQCcKT8F9JnFbTSItLR81/HLuu/WzHCKyKBitpRFvisgfrTI9cWt89eU70m14F9pu3SVVepegB8mUBpgnFcJWLctafpUotGgLZsOg9AdgNUO5cXvmpToD1v7vYGSknnYiwOI4KqBvs6n22PSBROO7ZaBde27kFXbrAZVKwQvf/Gd6CZWv7h5COt18RLhdOSIDQHm6Pkn4S5v+yUnzQ1Wqsep09I/0Zg1dZGtGirGhD60fzjw2iAnEL4KTZmzvvipAd5IG+CCDW8mEtbMdKzzSSLQVfcprMh9MRV+vh8tg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
